name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build the project
      - name: Build project
        run: bun run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required: Add this in GitHub Secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required: Add this in GitHub Secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required: Add this in GitHub Secrets
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}